### ISSUE TITLE
Add a car [FR]

### ISSUE THREAD

**Issue by NovaXen** [JovannMC/salad-simulator#1]
**Describe your request**
Add a buggy car what i can use to shoot myself into space

**Additional information**
This was a feature of the older salad simulator, should be added into this one

**How big of a priority is this**
Yes, if its not in the game I will not play it

**Comment by JovannMC** [comment]
Added in release 0.2a

You can't mess around with the car unlike the previous game yet unfortunately due to the new player controller system
